# Generated by Django 3.0.4 on 2020-05-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=30)),
                ('emp_id', models.IntegerField()),
                ('jobtype', models.CharField(max_length=256)),
            ],
        ),
    ]
